In [2]:
import scipy.constants as sc
import math as m
import numpy as np

In [13]:
m.exp(-70*10**3/sc.k*(-500/(1273*1773))/sc.N_A)*5

32.28217859092756

In [11]:
-70*10**3/sc.k*(-500/(1273*1773))/sc.N_A


1.8650774191155364

In [10]:
sc.N_A

6.022140857e+23

In [16]:
a=m.sqrt(10**-6/(4.97*10**-10))

In [22]:
(1/6)*(b)*(4.97e-10)**2

1.6666666666666665e-13

In [21]:
b=(1e-6/(4.97e-10))**2

In [24]:
b*(4.97e-10)

0.0020120724346076456

In [27]:
(6*(1.6e-28)*3/(4*m.pi))**(1/3)

6.119663483891746e-10

In [56]:
n0=1e-9/(1.6e-29)
#r0=3.36e-10
r0=6.11e-10
y=0.177
nr=n0*m.exp(-4*m.pi*y*(r0)**2/(sc.k*1356))

In [57]:
print(round(nr,0))
print(len(str(int(nr))))

3.0
1


In [55]:
n0

6.25e+19

In [63]:
dT=np.array([180,200,220])

dT**2

array([32400, 40000, 48400])

In [67]:
dT=np.array([180,200,220])
Tm=1356
Lm=1.88e9
f0=1e11
C0=6e28
dGv=16*m.pi*(y**3)*Tm**2/(3*(Lm)**2*(dT**2))
dGv

array([  1.49185657e-18,   1.20840382e-18,   9.98680842e-19])

In [68]:
r=2*y*Tm/(Lm*dT)
r

array([  1.41851064e-09,   1.27665957e-09,   1.16059961e-09])

In [71]:
theta=30/180*m.pi
f=(2-3*m.cos(theta)+(m.cos(theta))**3)/4
dGv*f

array([  1.91863352e-20,   1.55409315e-20,   1.28437451e-20])

In [86]:
N_r=[0,0,0]
for i in range(len(dGv)):
    print(i)
    N_r[i]=f0*C0*m.exp(-dGv[i]/(sc.k*(Tm-dT[i])))
    
N_r

0
1
2


[0.7477185146097094, 7877030.602511904, 1332556372145.5615]

In [83]:
dT[2]

220

In [87]:
N_r=f0*C0*m.exp(-dGv/(sc.k*(Tm-dT)))

TypeError: only length-1 arrays can be converted to Python scalars